name: Build OpenGL Project

on:
  workflow_dispatch:

  push:
    branches:
      - testci
  pull_request:
    branches:
      - testci

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Install Visual Studio Build Tools (Manual Download)
      shell: powershell
      run: |
        Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_buildtools.exe -OutFile vs_buildtools.exe
        Start-Process -Wait -NoNewWindow -FilePath "vs_buildtools.exe" -ArgumentList "--quiet", "--wait", "--norestart", "--nocache", "--add Microsoft.VisualStudio.Workload.VCTools"

    - name: Build project
      run: |
        cd cw
        "C:\\Program Files\\Microsoft Visual Studio\\2022\\BuildTools\\MSBuild\\Current\\Bin\\MSBuild.exe" cw.sln /p:Configuration=Release


  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake libgl1-mesa-dev

    - name: Configure and Build
      run: |
        cd cw
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make
